apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migrate
  namespace: game-backlog
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: game-backlog-api-migrate:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: gamebacklog-secrets
