apiVersion: v1
kind: Secret
metadata:
  name: gamebacklog-secrets
  namespace: game-backlog
type: Opaque
data:
  DATABASE_URL: ""
  JWT_SECRET: ""
  REDIS_URL: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: ""
  STEAM_API_KEY: ""
